### PR TITLE
Loading a Game

### PR DESCRIPTION
**Pull request by YoomamaFTW**
Seems like Kivy can't find the screen? But this is for loading a new or old game.

### CODE REVIEW

**Comment by YoomamaFTW** [comment]
I can't anymore. I pip installed black, ran through the file that needed reformatting and still get the error...

**Comment by Franccisco** [comment]
What's the status of this PR?

**Comment by YoomamaFTW** [comment]
@Franccisco This PR is all done. I would want to check the merge conflicts, but the other two linter checkers haven't been setup yet. So I can't merge PRs

**Comment by YoomamaFTW** [comment]
Yoom: PR is ready for production. The only concern is the plugboard's on_enter event. That area of 1) redoing the plug array to be even and 2) the resetting of all_plugs could coincide with wires. But I'm not sure. Those are untested precaution in case the user tampers with the JSON data.

**Pull request merged**
